# ProxyHawk Configuration

# General settings
timeout: 10                   # Timeout in seconds
insecure_skip_verify: true   # Skip TLS certificate verification
enable_cloud_checks: false   # Enable cloud provider checks
enable_anonymity_check: true # Enable proxy anonymity checks

# Interactsh settings
interactsh_url: "https://interact.sh"  # URL of the Interactsh server
interactsh_token: ""                   # Token for the Interactsh server (optional)

# User agent and headers
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
default_headers:
  Accept: "*/*"
  Connection: "keep-alive"
  User-Agent: "curl/7.64.1"

# Test URLs configuration
test_urls:
  default_url: "https://api.ipify.org?format=json"
  required_success_count: 1
  urls:
    - url: "https://api.ipify.org?format=json"
      description: "IP Check"
      required: true
    - url: "https://httpbin.org/ip"
      description: "HTTP Bin IP"
      required: false

# Validation settings
validation_url: "http://example.com"
min_response_bytes: 100
disallowed_keywords:
  - "Access Denied"
  - "Proxy Error"
  - "Bad Gateway"
  - "Gateway Timeout"
  - "Service Unavailable"

# Cloud provider configurations
cloud_providers:
  - name: "AWS"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://169.254.169.254/latest/meta-data/"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Amazon Technologies Inc."
      - "Amazon.com, Inc."
      - "Amazon Web Services"

  - name: "GCP"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://metadata.google.internal/computeMetadata/v1/"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Google LLC"
      - "Google Cloud"

  - name: "Azure"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://169.254.169.254/metadata/instance"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Microsoft Corporation"
      - "Microsoft Azure"

# Advanced security checks
advanced_checks:
  test_protocol_smuggling: false
  test_dns_rebinding: false
  test_ipv6: false
  test_http_methods: ["GET"]
  test_cache_poisoning: false
  test_host_header_injection: false

# Response validation settings
require_status_code: 200
require_content_match: ""
require_header_fields: [] 