# Prometheus configuration for ProxyHawk metrics
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ProxyHawk metrics
  - job_name: 'proxyhawk'
    static_configs:
      - targets: ['proxyhawk-metrics:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093