# ProxyHawk Default Configuration
# This is the main configuration file for ProxyHawk proxy checker

# General settings
timeout: 15                   # Timeout in seconds for proxy checks
insecure_skip_verify: true   # Skip TLS certificate verification for testing
enable_cloud_checks: false   # Enable cloud provider detection (requires additional setup)
enable_anonymity_check: true # Enable proxy anonymity detection
concurrency: 10              # Number of concurrent proxy checks

# Rate limiting settings (important for avoiding IP bans)
rate_limit_enabled: false    # Enable rate limiting between requests
rate_limit_delay: 1s         # Delay between requests (e.g. 500ms, 1s, 2s)
rate_limit_per_host: true    # Apply rate limiting per host instead of globally

# Interactsh settings for advanced testing (optional)
interactsh_url: "https://interact.sh"  # URL of the Interactsh server
interactsh_token: ""                   # Token for the Interactsh server (leave empty for public)

# User agent and HTTP headers
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
default_headers:
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.9"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"
  Cache-Control: "no-cache"
  Pragma: "no-cache"
  DNT: "1"

# Test URLs configuration
test_urls:
  default_url: "https://api.ipify.org?format=json"  # Primary test URL
  required_success_count: 1                         # Number of successful tests required
  urls:
    - url: "https://api.ipify.org?format=json"
      description: "IP Check Service"
      required: true
    - url: "https://httpbin.org/ip"
      description: "HTTP Bin IP Test"
      required: false
    - url: "http://ip-api.com/json/"
      description: "IP API Geolocation"
      required: false

# Validation settings
validation:
  min_response_bytes: 50      # Minimum response size to consider valid
  disallowed_keywords:        # Keywords that indicate proxy failure
    - "Access Denied"
    - "Proxy Error"
    - "Bad Gateway"
    - "Gateway Timeout"
    - "Service Unavailable"
    - "403 Forbidden"
    - "502 Bad Gateway"
    - "503 Service Unavailable"
    - "504 Gateway Timeout"
    - "Connection refused"
    - "Timed out"

# Response validation settings
require_status_code: 200      # Required HTTP status code (0 = any)
require_content_match: ""     # Required content in response (empty = any)
require_header_fields: []     # Required headers in response

# Cloud provider configurations (for cloud detection)
cloud_providers:
  - name: "AWS"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://169.254.169.254/latest/meta-data/"
      - "http://169.254.169.254/latest/dynamic/instance-identity/"
    metadata_headers:
      "X-aws-ec2-metadata-token-ttl-seconds": "21600"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Amazon Technologies Inc."
      - "Amazon.com, Inc."
      - "Amazon Web Services"

  - name: "GCP"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://metadata.google.internal/computeMetadata/v1/"
      - "http://metadata/computeMetadata/v1/"
    metadata_headers:
      "Metadata-Flavor": "Google"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Google LLC"
      - "Google Cloud"

  - name: "Azure"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://169.254.169.254/metadata/instance"
      - "http://169.254.169.254/metadata/identity"
    metadata_headers:
      "Metadata": "true"
      "User-Agent": "curl/7.64.0"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Microsoft Corporation"
      - "Microsoft Azure"

  - name: "DigitalOcean"
    metadata_ips:
      - "169.254.169.254"
    metadata_urls:
      - "http://169.254.169.254/metadata/v1/"
    metadata_headers:
      "Metadata-Token": "do-metadata"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "DigitalOcean, LLC"
      - "DigitalOcean"

# Advanced security checks (disabled by default)
advanced_checks:
  test_protocol_smuggling: false    # Test for HTTP request smuggling
  test_dns_rebinding: false         # Test for DNS rebinding vulnerabilities
  test_ipv6: false                  # Test IPv6 connectivity
  test_http_methods: ["GET"]        # HTTP methods to test
  test_cache_poisoning: false       # Test for cache poisoning
  test_host_header_injection: false # Test for host header injection
  disable_interactsh: false         # Disable Interactsh testing