# ProxyHawk Production Configuration
# Optimized settings for production proxy validation

# General settings - more conservative for production
timeout: 10                   # Shorter timeout for faster processing
insecure_skip_verify: false   # Verify TLS certificates in production
enable_cloud_checks: true     # Enable cloud provider detection
enable_anonymity_check: true  # Always check anonymity in production
concurrency: 5                # Lower concurrency to be respectful

# Rate limiting - enabled for production to avoid bans
rate_limit_enabled: true      # Always enable rate limiting in production
rate_limit_delay: 2s          # 2 second delay between requests
rate_limit_per_host: true     # Per-host rate limiting

# Production user agent
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
default_headers:
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.9"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"
  Cache-Control: "no-cache"
  Upgrade-Insecure-Requests: "1"
  Sec-Fetch-Dest: "document"
  Sec-Fetch-Mode: "navigate"
  Sec-Fetch-Site: "none"

# Multiple test URLs for reliability
test_urls:
  default_url: "https://api.ipify.org?format=json"
  required_success_count: 2     # Require 2 successful tests for validation
  urls:
    - url: "https://api.ipify.org?format=json"
      description: "Primary IP Check"
      required: true
    - url: "https://httpbin.org/ip"
      description: "Secondary IP Check"
      required: true
    - url: "https://ipinfo.io/json"
      description: "IP Info Check"
      required: false

# Stricter validation for production
validation:
  min_response_bytes: 100      # Higher minimum response size
  disallowed_keywords:
    - "Access Denied"
    - "Proxy Error"
    - "Bad Gateway"
    - "Gateway Timeout"
    - "Service Unavailable"
    - "403 Forbidden"
    - "502 Bad Gateway"
    - "503 Service Unavailable"
    - "504 Gateway Timeout"
    - "Connection refused"
    - "Timed out"
    - "VPN detected"
    - "Proxy detected"
    - "Blocked"
    - "Geo-blocked"
    - "Not available in your region"

# Require 200 status for production
require_status_code: 200
require_content_match: ""
require_header_fields: []

# Full cloud provider detection enabled
cloud_providers:
  - name: "AWS"
    metadata_ips: ["169.254.169.254"]
    metadata_urls:
      - "http://169.254.169.254/latest/meta-data/"
      - "http://169.254.169.254/latest/dynamic/instance-identity/"
    metadata_headers:
      "X-aws-ec2-metadata-token-ttl-seconds": "21600"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Amazon Technologies Inc."
      - "Amazon.com, Inc."
      - "Amazon Web Services"

  - name: "GCP"
    metadata_ips: ["169.254.169.254"]
    metadata_urls:
      - "http://metadata.google.internal/computeMetadata/v1/"
    metadata_headers:
      "Metadata-Flavor": "Google"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Google LLC"
      - "Google Cloud"

  - name: "Azure"
    metadata_ips: ["169.254.169.254"]
    metadata_urls:
      - "http://169.254.169.254/metadata/instance"
    metadata_headers:
      "Metadata": "true"
    internal_ranges:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    org_names:
      - "Microsoft Corporation"
      - "Microsoft Azure"

# Advanced checks disabled by default in production for speed
advanced_checks:
  test_protocol_smuggling: false
  test_dns_rebinding: false
  test_ipv6: false
  test_http_methods: ["GET"]
  test_cache_poisoning: false
  test_host_header_injection: false
  disable_interactsh: true      # Disable Interactsh for faster processing